# -*- coding: utf-8 -*-
"""appmc.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FBKnOuZVQWMG2eTQ8bzj8Vn6fuGIdiFm
"""

# ============================================================
# APP STREAMLIT - MONTE CARLO PARA ACCIONES
# ============================================================

import streamlit as st
import yfinance as yf
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt


# ============================================================
# CONFIGURACIÓN
# ============================================================

st.set_page_config(
    page_title="Monte Carlo - Acciones",
    page_icon="📈",
    layout="wide"
)


# ============================================================
# TÍTULO
# ============================================================

st.title("📈 Simulador Monte Carlo de Acciones")

st.write(
    """
    Esta aplicación estima posibles precios futuros de una acción
    mediante una simulación de Monte Carlo basada en los rendimientos
    logarítmicos históricos.
    """
)


# ============================================================
# SIDEBAR - PARÁMETROS
# ============================================================

st.sidebar.header("Parámetros del modelo")


# Clave de pizarra
ticker = st.sidebar.text_input(
    "Clave de pizarra de Yahoo Finance",
    value="GCARSOA1.MX"
).upper().strip()


# Periodo histórico
periodo_opciones = {
    "1 mes": "1mo",
    "3 meses": "3mo",
    "6 meses": "6mo",
    "1 año": "1y",
    "2 años": "2y",
    "5 años": "5y",
    "10 años": "10y",
    "Máximo disponible": "max"
}

periodo_nombre = st.sidebar.selectbox(
    "Periodo histórico",
    list(periodo_opciones.keys()),
    index=4
)

periodo = periodo_opciones[periodo_nombre]


# Días futuros
dias_futuros = st.sidebar.number_input(
    "Días futuros",
    min_value=1,
    max_value=1000,
    value=50,
    step=1
)


# Simulaciones
simulaciones = st.sidebar.number_input(
    "Número de simulaciones",
    min_value=1000,
    max_value=50000,
    value=10000,
    step=1000
)


# Botón
ejecutar = st.sidebar.button(
    "Ejecutar Monte Carlo",
    type="primary"
)


# ============================================================
# FUNCIÓN PARA OBTENER DATOS
# ============================================================

def obtener_precios(ticker, periodo):

    data = yf.download(
        ticker,
        period=periodo,
        auto_adjust=True,
        progress=False
    )

    if data.empty:
        return None

    # Manejar posibles MultiIndex de yfinance
    if isinstance(data.columns, pd.MultiIndex):

        if "Close" in data.columns.get_level_values(0):
            precios = data["Close"]

            # Si queda DataFrame, seleccionar primera columna
            if isinstance(precios, pd.DataFrame):
                precios = precios.iloc[:, 0]

        else:
            return None

    else:

        if "Close" not in data.columns:
            return None

        precios = data["Close"]

    precios = pd.Series(precios).dropna()

    return precios


# ============================================================
# EJECUCIÓN
# ============================================================

if ejecutar:

    with st.spinner("Descargando datos y ejecutando simulaciones..."):

        try:

            # ==================================================
            # DATOS HISTÓRICOS
            # ==================================================

            precios = obtener_precios(
                ticker,
                periodo
            )

            if precios is None or len(precios) < 30:

                st.error(
                    "No se pudieron obtener suficientes datos "
                    "históricos para este ticker."
                )

                st.stop()


            # ==================================================
            # PRECIO ACTUAL
            # ==================================================

            precio_actual = float(
                precios.iloc[-1]
            )


            # ==================================================
            # RENDIMIENTOS LOGARÍTMICOS
            # ==================================================

            rendimientos = np.log(
                precios / precios.shift(1)
            ).dropna()


            mu = float(
                rendimientos.mean()
            )

            sigma = float(
                rendimientos.std()
            )


            # ==================================================
            # MONTE CARLO
            # ==================================================

            np.random.seed(42)

            Z = np.random.normal(
                0,
                1,
                (
                    dias_futuros,
                    simulaciones
                )
            )


            simulaciones_precios = np.zeros(
                (
                    dias_futuros + 1,
                    simulaciones
                )
            )


            simulaciones_precios[0, :] = precio_actual


            for t in range(
                1,
                dias_futuros + 1
            ):

                simulaciones_precios[t, :] = (
                    simulaciones_precios[t - 1, :]
                    *
                    np.exp(
                        (mu - 0.5 * sigma**2)
                        +
                        sigma * Z[t - 1, :]
                    )
                )


            # ==================================================
            # PRECIOS FINALES
            # ==================================================

            precios_finales = (
                simulaciones_precios[-1, :]
            )


            p5 = np.percentile(
                precios_finales,
                5
            )

            p25 = np.percentile(
                precios_finales,
                25
            )

            p50 = np.percentile(
                precios_finales,
                50
            )

            p75 = np.percentile(
                precios_finales,
                75
            )

            p95 = np.percentile(
                precios_finales,
                95
            )


            precio_esperado = np.mean(
                precios_finales
            )


            # ==================================================
            # PROBABILIDAD DE GANANCIA
            # ==================================================

            prob_ganar = np.mean(
                precios_finales > precio_actual
            )


            # ==================================================
            # RENDIMIENTO ESPERADO
            # ==================================================

            rendimiento_esperado = (
                precio_esperado / precio_actual
                - 1
            )


            rendimiento_mediana = (
                p50 / precio_actual
                - 1
            )


            # ==================================================
            # RESULTADOS PRINCIPALES
            # ==================================================

            st.success(
                f"Simulación completada para {ticker}"
            )


            st.subheader(
                f"Resultados para {ticker}"
            )


            col1, col2, col3, col4 = st.columns(4)


            col1.metric(
                "Precio actual",
                f"${precio_actual:,.2f}"
            )


            col2.metric(
                "Precio esperado",
                f"${precio_esperado:,.2f}",
                f"{rendimiento_esperado:.2%}"
            )


            col3.metric(
                "Mediana",
                f"${p50:,.2f}",
                f"{rendimiento_mediana:.2%}"
            )


            col4.metric(
                "Prob. de ganar",
                f"{prob_ganar:.2%}"
            )


            # ==================================================
            # TABLA DE PERCENTILES
            # ==================================================

            st.subheader(
                "Distribución de precios futuros"
            )


            resultados = pd.DataFrame({

                "Percentil": [
                    "P5",
                    "P25",
                    "P50 - Mediana",
                    "P75",
                    "P95"
                ],

                "Precio": [
                    p5,
                    p25,
                    p50,
                    p75,
                    p95
                ],

                "Rendimiento": [

                    p5 / precio_actual - 1,

                    p25 / precio_actual - 1,

                    p50 / precio_actual - 1,

                    p75 / precio_actual - 1,

                    p95 / precio_actual - 1

                ]

            })


            resultados["Precio"] = (
                resultados["Precio"]
                .map(lambda x: f"${x:,.2f}")
            )


            resultados["Rendimiento"] = (
                resultados["Rendimiento"]
                .map(lambda x: f"{x:.2%}")
            )


            st.dataframe(
                resultados,
                use_container_width=True,
                hide_index=True
            )


            # ==================================================
            # ESTADÍSTICAS DEL MODELO
            # ==================================================

            st.subheader(
                "Parámetros estimados"
            )


            col1, col2, col3 = st.columns(3)


            col1.metric(
                "μ diario",
                f"{mu:.5%}"
            )


            col2.metric(
                "σ diaria",
                f"{sigma:.5%}"
            )


            col3.metric(
                "Observaciones",
                f"{len(precios):,}"
            )


            # ==================================================
            # GRÁFICA MONTE CARLO
            # ==================================================

            st.subheader(
                "Trayectorias simuladas"
            )


            fig1, ax1 = plt.subplots(
                figsize=(12, 6)
            )


            # Mostrar máximo 100 trayectorias
            n_graficas = min(
                100,
                simulaciones
            )


            for i in range(
                n_graficas
            ):

                ax1.plot(
                    simulaciones_precios[:, i],
                    alpha=0.15
                )


            ax1.axhline(
                precio_actual,
                linestyle="--",
                label="Precio actual"
            )


            ax1.set_title(
                f"Monte Carlo - {ticker}"
            )

            ax1.set_xlabel(
                "Días futuros"
            )

            ax1.set_ylabel(
                "Precio"
            )

            ax1.legend()


            st.pyplot(
                fig1
            )


            # ==================================================
            # DISTRIBUCIÓN PRECIO FINAL
            # ==================================================

            st.subheader(
                "Distribución del precio final"
            )


            fig2, ax2 = plt.subplots(
                figsize=(12, 6)
            )


            ax2.hist(
                precios_finales,
                bins=100
            )


            ax2.axvline(
                p50,
                linestyle="--",
                label="Mediana"
            )


            ax2.axvline(
                p5,
                linestyle="--",
                label="P5"
            )


            ax2.axvline(
                p95,
                linestyle="--",
                label="P95"
            )


            ax2.axvline(
                precio_actual,
                linestyle=":",
                label="Precio actual"
            )


            ax2.set_title(
                f"Distribución del precio futuro - {ticker}"
            )


            ax2.set_xlabel(
                "Precio"
            )


            ax2.set_ylabel(
                "Frecuencia"
            )


            ax2.legend()


            st.pyplot(
                fig2
            )


            # ==================================================
            # INTERPRETACIÓN
            # ==================================================

            st.subheader(
                "Interpretación"
            )


            if prob_ganar >= 0.60:

                st.success(
                    f"""
                    La simulación estima una probabilidad de
                    **{prob_ganar:.2%}** de que el precio termine
                    por encima del precio actual después de
                    **{dias_futuros} días**.
                    """
                )

            elif prob_ganar >= 0.50:

                st.info(
                    f"""
                    La simulación muestra una probabilidad de
                    **{prob_ganar:.2%}** de terminar por encima
                    del precio actual. La señal es relativamente
                    neutral.
                    """
                )

            else:

                st.warning(
                    f"""
                    La simulación estima una probabilidad de sólo
                    **{prob_ganar:.2%}** de terminar por encima
                    del precio actual.
                    """
                )


            st.caption(
                """
                ⚠️ El modelo utiliza un movimiento browniano geométrico
                basado en rendimientos históricos. Los resultados son
                escenarios simulados y no constituyen una predicción
                ni una recomendación de inversión.
                """
            )


        except Exception as e:

            st.error(
                f"Ocurrió un error: {e}"
            )


# ============================================================
# PANTALLA INICIAL
# ============================================================

else:

    st.info(
        """
        Introduce una clave de pizarra de Yahoo Finance,
        selecciona el periodo histórico y los días futuros.
        Después pulsa **Ejecutar Monte Carlo**.
        """
    )


    st.markdown(
        """
        ### Ejemplos de claves de pizarra

        - `GCARSOA1.MX` — Grupo Carso
        - `FEMSAUBD.MX` — FEMSA
        - `WALMEX.MX` — Walmart México
        - `GMEXICOB.MX` — Grupo México
        - `BIMBOA.MX` — Grupo Bimbo
        - `GAPB.MX` — Grupo Aeroportuario del Pacífico
        """
    )